services:
  mongo1:
    image: mongo
    container_name: mongo1
    ports:
      - "27020:27017"
    command: ["mongod", "--replSet", "rs0"]
    networks:
      - mongo-cluster

  mongo2:
    image: mongo
    container_name: mongo2
    ports:
      - "27018:27017"
    command: ["mongod", "--replSet", "rs0"]
    networks:
      - mongo-cluster

  mongo3:
    image: mongo
    container_name: mongo3
    ports:
      - "27019:27017"
    command: ["mongod", "--replSet", "rs0"]
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge